# Site settings
title: xxx
email: shengqiu2014@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
 Be a data scientist using python
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
